# Site settings
title: Vertigo Solutions LLP
email: info@vertigosolutions.in
description: > # this means to ignore newlines until "baseurl:"
  Vertigo is working hard towards creating simple technology products which can encapsulate complex business logic.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vertigosolutions.in" # the base hostname & protocol for your site
twitter_username: consultvertigo
github_username:

# Build settings
markdown: kramdown
